In [6]:
from google.colab import files
uploaded = files.upload()

Saving olist_customers_dataset.csv to olist_customers_dataset (1).csv
Saving olist_order_items_dataset.csv to olist_order_items_dataset (1).csv
Saving olist_orders_dataset.csv to olist_orders_dataset (1).csv

In [7]:
import pandas as pd
import zipfile
import os

In [13]:
orders = pd.read_csv('/content/olist_orders_dataset.csv')
order_items = pd.read_csv('/content/olist_order_items_dataset.csv')
customers = pd.read_csv('/content/olist_customers_dataset.csv')

In [14]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [15]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [16]:
orders.describe(include='all')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-08-02 12:06:07,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [17]:
orders_clean = orders[orders['order_status'] == 'delivered'].copy()

In [18]:
orders_clean['order_purchase_timestamp'] = pd.to_datetime(orders_clean['order_purchase_timestamp'])

In [19]:
orders_clean = orders_clean[['order_id', 'customer_id', 'order_purchase_timestamp']]

In [20]:
order_items_clean = order_items[['order_id', 'price']].copy()

In [21]:
order_items_clean = order_items_clean.groupby('order_id', as_index=False)['price'].sum()

In [22]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [23]:
customers_clean = customers[['customer_id', 'customer_unique_id']].copy()

In [ ]:
print(orders_clean.shape)
orders_clean.head()

(96478, 3)

,order_id,customer_id,order_purchase_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39

In [24]:
print(order_items_clean.shape)
order_items_clean.head()

(98666, 2)

                           order_id   price
0  00010242fe8c5a6d1ba2dd792cb16214   58.90
1  00018f77f2f0320c557190d7a144bdd3  239.90
2  000229ec398224ef6ca0657da4fc703e  199.00
3  00024acbcdf0a6daa1e931b038114c75   12.99
4  00042b26cf59d7ce69dfabb4e55b4fd9  199.90

In [25]:
print(customers_clean.shape)
customers_clean.head()

(99441, 2)

                        customer_id                customer_unique_id
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

In [26]:
orders_customers = orders_clean.merge(customers_clean, on='customer_id', how='inner')

In [27]:
tabla_maestra = orders_customers.merge(order_items_clean, on='order_id', how='inner')

In [28]:
tabla_maestra = tabla_maestra[['customer_unique_id', 'order_purchase_timestamp', 'price']]

In [29]:
print(tabla_maestra.shape)
tabla_maestra.head()

(96478, 3)

                 customer_unique_id order_purchase_timestamp   price
0  7c396fd4830fd04220f754e42b4e5bff      2017-10-02 10:56:33   29.99
1  af07308b275d755c9edb36a90c618231      2018-07-24 20:41:37  118.70
2  3a653a41f6f9fc3d2a113cf8398680e8      2018-08-08 08:38:49  159.90
3  7c142cf63193a1473d2e66489a9ae977      2017-11-18 19:28:06   45.00
4  72632f0f9dd73dfee390c9b22eb56dd6      2018-02-13 21:18:39   19.90

In [30]:
fecha_referencia = tabla_maestra['order_purchase_timestamp'].max() + pd.Timedelta(days=1)
print(fecha_referencia)

2018-08-30 15:00:37

In [31]:
rfm = tabla_maestra.groupby('customer_unique_id').agg(
    recencia=('order_purchase_timestamp', lambda x: (fecha_referencia - x.max()).days),
    frecuencia=('order_purchase_timestamp', 'count'),
    monetario=('price', 'sum')
).reset_index()

In [32]:
print(rfm.shape)
rfm.head(10)

(93358, 4)

                 customer_unique_id  recencia  frecuencia  monetario
0  0000366f3b9a7992bf8c76cfdf3221e2       112           1     129.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f       115           1      18.90
2  0000f46a3911fa3c0805444483337064       537           1      69.00
3  0000f6ccb0745a6a4b88665a16c9f078       321           1      25.99
4  0004aac84e0df4da2b147fca70cf8255       288           1     180.00
5  0004bd2a26a76fe21f786e4fbd80607f       146           1     154.00
6  00050ab1314c0e55a6ca13cf7181fecf       132           1      27.99
7  00053a61a98854899e70ed204dd4bafe       183           1     382.00
8  0005e1862207bf6ccc02e4228effd9a0       543           1     135.00
9  0005ef4cd20d2893f0d9fbd94d3c0d97       170           1     104.90

In [33]:
rfm['r_score'] = pd.qcut(rfm['recencia'], 5, labels=[5, 4, 3, 2, 1])

In [34]:
rfm['f_score'] = pd.qcut(rfm['frecuencia'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5])

In [35]:
rfm['m_score'] = pd.qcut(rfm['monetario'], 5, labels=[1, 2, 3, 4, 5])

In [36]:
print(rfm.head(10))

                 customer_unique_id  recencia  frecuencia  monetario r_score  \
0  0000366f3b9a7992bf8c76cfdf3221e2       112           1     129.90       4
1  0000b849f77a49e4a4ce2b2a4ca5be3f       115           1      18.90       4
2  0000f46a3911fa3c0805444483337064       537           1      69.00       1
3  0000f6ccb0745a6a4b88665a16c9f078       321           1      25.99       2
4  0004aac84e0df4da2b147fca70cf8255       288           1     180.00       2
5  0004bd2a26a76fe21f786e4fbd80607f       146           1     154.00       4
6  00050ab1314c0e55a6ca13cf7181fecf       132           1      27.99       4
7  00053a61a98854899e70ed204dd4bafe       183           1     382.00       3
8  0005e1862207bf6ccc02e4228effd9a0       543           1     135.00       1
9  0005ef4cd20d2893f0d9fbd94d3c0d97       170           1     104.90       4

  f_score m_score
0       1       4
1       1       1
2       1       2
3       1       1
4       1       5
5       1       4
6       1       1
7       1       5
8       1       4
9       1       3

In [37]:
rfm['rfm_score'] = rfm['r_score'].astype(str) + rfm['f_score'].astype(str) + rfm['m_score'].astype(str)

In [38]:
rfm['rfm_promedio'] = rfm[['r_score', 'f_score', 'm_score']].astype(int).mean(axis=1)

In [39]:
rfm.head(10)

,customer_unique_id,recencia,frecuencia,monetario,r_score,f_score,m_score,rfm_score,rfm_promedio
0,0000366f3b9a7992bf8c76cfdf3221e2,112,1,129.90,4,1,4,414,3.000000
1,0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,18.90,4,1,1,411,2.000000
2,0000f46a3911fa3c0805444483337064,537,1,69.00,1,1,2,112,1.333333
3,0000f6ccb0745a6a4b88665a16c9f078,321,1,25.99,2,1,1,211,1.333333
4,0004aac84e0df4da2b147fca70cf8255,288,1,180.00,2,1,5,215,2.666667
5,0004bd2a26a76fe21f786e4fbd80607f,146,1,154.00,4,1,4,414,3.000000
6,00050ab1314c0e55a6ca13cf7181fecf,132,1,27.99,4,1,1,411,2.000000
7,00053a61a98854899e70ed204dd4bafe,183,1,382.00,3,1,5,315,3.000000
8,0005e1862207bf6ccc02e4228effd9a0,543,1,135.00,1,1,4,114,2.000000
9,0005ef4cd20d2893f0d9fbd94d3c0d97,170,1,104.90,4,1,3,413,2.666667

In [40]:
def asignar_segmento(row):
    r = int(row['r_score'])
    f = int(row['f_score'])

    if r >= 4 and f >= 4:
        return 'Champions'
    elif r >= 4 and f < 4:
        return 'Nuevos / Prometedores'
    elif r < 4 and f >= 4:
        return 'Leales en riesgo'
    elif r <= 2 and f <= 2:
        return 'Perdidos'
    else:
        return 'En riesgo'

rfm['segmento'] = rfm.apply(asignar_segmento, axis=1)

In [41]:
rfm.head(10)

,customer_unique_id,recencia,frecuencia,monetario,r_score,f_score,m_score,rfm_score,rfm_promedio,segmento
0,0000366f3b9a7992bf8c76cfdf3221e2,112,1,129.90,4,1,4,414,3.000000,Nuevos / Prometedores
1,0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,18.90,4,1,1,411,2.000000,Nuevos / Prometedores
2,0000f46a3911fa3c0805444483337064,537,1,69.00,1,1,2,112,1.333333,Perdidos
3,0000f6ccb0745a6a4b88665a16c9f078,321,1,25.99,2,1,1,211,1.333333,Perdidos
4,0004aac84e0df4da2b147fca70cf8255,288,1,180.00,2,1,5,215,2.666667,Perdidos
5,0004bd2a26a76fe21f786e4fbd80607f,146,1,154.00,4,1,4,414,3.000000,Nuevos / Prometedores
6,00050ab1314c0e55a6ca13cf7181fecf,132,1,27.99,4,1,1,411,2.000000,Nuevos / Prometedores
7,00053a61a98854899e70ed204dd4bafe,183,1,382.00,3,1,5,315,3.000000,En riesgo
8,0005e1862207bf6ccc02e4228effd9a0,543,1,135.00,1,1,4,114,2.000000,Perdidos
9,0005ef4cd20d2893f0d9fbd94d3c0d97,170,1,104.90,4,1,3,413,2.666667,Nuevos / Prometedores

In [42]:
rfm['segmento'].value_counts()

segmento
Nuevos / Prometedores    22472
Leales en riesgo         22382
En riesgo                18557
Perdidos                 14986
Champions                14961
Name: count, dtype: int64

In [43]:
def score_frecuencia(f):
    if f == 1:
        return 1
    elif f == 2:
        return 2
    elif f == 3:
        return 3
    elif f in [4, 5]:
        return 4
    else:
        return 5

rfm['f_score'] = rfm['frecuencia'].apply(score_frecuencia)

In [44]:
rfm['rfm_score'] = rfm['r_score'].astype(str) + rfm['f_score'].astype(str) + rfm['m_score'].astype(str)
rfm['rfm_promedio'] = rfm[['r_score', 'f_score', 'm_score']].astype(int).mean(axis=1)
rfm['segmento'] = rfm.apply(asignar_segmento, axis=1)

rfm['segmento'].value_counts()

segmento
Nuevos / Prometedores    37400
Perdidos                 37147
En riesgo                18764
Champions                   33
Leales en riesgo            14
Name: count, dtype: int64

In [45]:
def asignar_segmento(row):
    r = int(row['r_score'])
    f = int(row['f_score'])
    m = int(row['m_score'])

    if f >= 3:
        return 'Recurrentes / Leales'
    elif r >= 4 and m >= 4:
        return 'Nuevos de alto valor'
    elif r >= 4:
        return 'Nuevos / Recientes'
    elif r <= 2 and m <= 2:
        return 'Perdidos'
    else:
        return 'En riesgo'

rfm['segmento'] = rfm.apply(asignar_segmento, axis=1)

In [46]:
rfm['rfm_score'] = rfm['r_score'].astype(str) + rfm['f_score'].astype(str) + rfm['m_score'].astype(str)
rfm['rfm_promedio'] = rfm[['r_score', 'f_score', 'm_score']].astype(int).mean(axis=1)
rfm['segmento'] = rfm.apply(asignar_segmento, axis=1)

rfm['segmento'].value_counts()

segmento
En riesgo               39975
Nuevos / Recientes      22036
Perdidos                15844
Nuevos de alto valor    15275
Recurrentes / Leales      228
Name: count, dtype: int64

In [47]:
tabla_maestra['mes_compra'] = tabla_maestra['order_purchase_timestamp'].dt.to_period('M')

In [48]:
tabla_maestra['cohorte'] = tabla_maestra.groupby('customer_unique_id')['mes_compra'].transform('min')

In [49]:
tabla_maestra['periodo_cohorte'] = (tabla_maestra['mes_compra'] - tabla_maestra['cohorte']).apply(lambda x: x.n)

In [50]:
tabla_maestra[['customer_unique_id', 'mes_compra', 'cohorte', 'periodo_cohorte']].head(10)

                 customer_unique_id mes_compra  cohorte  periodo_cohorte
0  7c396fd4830fd04220f754e42b4e5bff    2017-10  2017-09                1
1  af07308b275d755c9edb36a90c618231    2018-07  2018-07                0
2  3a653a41f6f9fc3d2a113cf8398680e8    2018-08  2018-08                0
3  7c142cf63193a1473d2e66489a9ae977    2017-11  2017-11                0
4  72632f0f9dd73dfee390c9b22eb56dd6    2018-02  2018-02                0
5  80bb27c7c16e8f973207a5086ab329e2    2017-07  2017-07                0
6  932afa1e708222e5821dac9cd5db4cae    2017-05  2017-05                0
7  39382392765b6dc74812866ee5ee92a7    2017-01  2017-01                0
8  299905e3934e9e181bfb2e164dd4b4f8    2017-07  2017-07                0
9  f2a85dec752b8517b5e58a06ff3cd937    2017-05  2017-05                0

In [51]:
cohorte_data = tabla_maestra.groupby(['cohorte', 'periodo_cohorte'])['customer_unique_id'].nunique().reset_index()

In [52]:
cohorte_pivot = cohorte_data.pivot(index='cohorte', columns='periodo_cohorte', values='customer_unique_id')

In [53]:
cohorte_pivot

periodo_cohorte,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20
cohorte,,,,,,,,,,,,,,,,,,,,
2016-09,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,262.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,2.0,2.0
2016-12,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,717.0,2.0,2.0,1.0,3.0,1.0,3.0,1.0,1.0,NaN,3.0,1.0,5.0,3.0,1.0,1.0,2.0,3.0,1.0,NaN
2017-02,1628.0,3.0,5.0,2.0,7.0,2.0,4.0,3.0,2.0,3.0,2.0,5.0,2.0,3.0,2.0,1.0,1.0,3.0,NaN,NaN
2017-03,2503.0,11.0,9.0,10.0,9.0,4.0,4.0,8.0,8.0,2.0,9.0,3.0,5.0,3.0,4.0,6.0,2.0,3.0,NaN,NaN
2017-04,2256.0,14.0,5.0,4.0,6.0,6.0,8.0,7.0,7.0,4.0,6.0,2.0,1.0,1.0,2.0,2.0,3.0,NaN,NaN,NaN
2017-05,3451.0,16.0,16.0,10.0,10.0,11.0,14.0,5.0,9.0,9.0,9.0,12.0,8.0,1.0,6.0,7.0,NaN,NaN,NaN,NaN
2017-06,3037.0,15.0,12.0,13.0,9.0,12.0,11.0,7.0,4.0,6.0,9.0,11.0,5.0,5.0,7.0,NaN,NaN,NaN,NaN,NaN
2017-07,3752.0,20.0,13.0,9.0,11.0,8.0,12.0,4.0,7.0,10.0,8.0,11.0,5.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,4057.0,28.0,14.0,11.0,14.0,21.0,12.0,11.0,6.0,6.0,10.0,8.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,4004.0,28.0,22.0,11.0,18.0,9.0,9.0,10.0,11.0,7.0,10.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,4328.0,31.0,11.0,4.0,10.0,9.0,9.0,16.0,12.0,8.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,7060.0,40.0,26.0,12.0,12.0,13.0,8.0,13.0,9.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,5338.0,11.0,15.0,18.0,14.0,11.0,9.0,1.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,6842.0,23.0,25.0,20.0,20.0,11.0,12.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,6288.0,22.0,25.0,19.0,16.0,14.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,6774.0,27.0,20.0,20.0,8.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,6582.0,39.0,20.0,16.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,6506.0,34.0,17.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,5878.0,25.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,5949.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,6144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
tamano_cohorte = cohorte_pivot[0]
retencion = cohorte_pivot.divide(tamano_cohorte, axis=0) * 100

In [55]:
retencion.round(1)

periodo_cohorte,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20
cohorte,,,,,,,,,,,,,,,,,,,,
2016-09,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-10,100.0,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,0.4,NaN,0.4,NaN,0.4,NaN,0.4,NaN,0.4,0.8,0.8
2016-12,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-01,100.0,0.3,0.3,0.1,0.4,0.1,0.4,0.1,0.1,NaN,0.4,0.1,0.7,0.4,0.1,0.1,0.3,0.4,0.1,NaN
2017-02,100.0,0.2,0.3,0.1,0.4,0.1,0.2,0.2,0.1,0.2,0.1,0.3,0.1,0.2,0.1,0.1,0.1,0.2,NaN,NaN
2017-03,100.0,0.4,0.4,0.4,0.4,0.2,0.2,0.3,0.3,0.1,0.4,0.1,0.2,0.1,0.2,0.2,0.1,0.1,NaN,NaN
2017-04,100.0,0.6,0.2,0.2,0.3,0.3,0.4,0.3,0.3,0.2,0.3,0.1,0.0,0.0,0.1,0.1,0.1,NaN,NaN,NaN
2017-05,100.0,0.5,0.5,0.3,0.3,0.3,0.4,0.1,0.3,0.3,0.3,0.3,0.2,0.0,0.2,0.2,NaN,NaN,NaN,NaN
2017-06,100.0,0.5,0.4,0.4,0.3,0.4,0.4,0.2,0.1,0.2,0.3,0.4,0.2,0.2,0.2,NaN,NaN,NaN,NaN,NaN
2017-07,100.0,0.5,0.3,0.2,0.3,0.2,0.3,0.1,0.2,0.3,0.2,0.3,0.1,0.2,NaN,NaN,NaN,NaN,NaN,NaN
2017-08,100.0,0.7,0.3,0.3,0.3,0.5,0.3,0.3,0.1,0.1,0.2,0.2,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-09,100.0,0.7,0.5,0.3,0.4,0.2,0.2,0.2,0.3,0.2,0.2,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-10,100.0,0.7,0.3,0.1,0.2,0.2,0.2,0.4,0.3,0.2,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11,100.0,0.6,0.4,0.2,0.2,0.2,0.1,0.2,0.1,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12,100.0,0.2,0.3,0.3,0.3,0.2,0.2,0.0,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01,100.0,0.3,0.4,0.3,0.3,0.2,0.2,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02,100.0,0.3,0.4,0.3,0.3,0.2,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03,100.0,0.4,0.3,0.3,0.1,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04,100.0,0.6,0.3,0.2,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05,100.0,0.5,0.3,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-06,100.0,0.4,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07,100.0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
retencion.round(1).style.background_gradient(cmap='Greens', axis=None)

In [57]:
rfm.to_csv('rfm_resultado.csv', index=False)

In [58]:
retencion.round(1).reset_index().to_csv('cohortes_resultado.csv', index=False)

In [60]:
from google.colab import files
files.download('rfm_resultado.csv')
files.download('cohortes_resultado.csv')